apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waed-be-demo
  namespace: waed-test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: waed-test
  project: default
  source:
    chart: waed-template
    helm:
      releaseName: waed-be
      valueFiles:
      - waed-be-demo-values.yaml
    repoURL: https://cm.devopsars.com
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true